all:
	gcc main.c -I/usr/include/SDL2 -lSDL2main -lSDL2 -lSDL2_image -o test1
	gcc physics.c -I/usr/include/SDL2 -I/usr/include/chipmunk -lSDL2main -lSDL2 -lSDL2_image -lchipmunk -o test2
clean:
	rm -f test1 test2 test3
